### ISSUE TITLE
[bug] Authors quote appearing in various situtations

### ISSUE THREAD

**Issue by Szybet** [Kobo-InkBox/inkbox#21] opened 2022-03-22 21:36 UTC
Image of the bug:
![IMG_20220322_222906](https://user-images.githubusercontent.com/53944559/159580121-fbda465d-4343-47ea-b616-09c62dd22434.jpg)

Most often when canceling file chooser. In my opinion Global reading settings doesn't affect this. I have disabled authors quotes in settings

**Comment by tux-linux** [comment] 2022-03-22 21:56
Duplicate of #19.

**Closed by tux-linux** 2022-03-22 21:56 UTC
